import { Poppins } from "next/font/google";

import "../styles/globals.css";
import Providers from "@/lib/providers";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <Header />
          <div className="max-w-5xl m-auto w-full px-4 py-2">
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
