import { getServerSession } from "next-auth";
import Providers from "@/lib/providers";
import SessionProvider from "@/lib/SessionProvider";

import { Poppins } from "next/font/google";
import "@/styles/globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <SessionProvider session={session}>
            <Header />
            <div className="max-w-5xl m-auto w-full px-4 py-2">
              {children}
              <Footer />
            </div>
          </SessionProvider>
        </Providers>
      </body>
    </html>
  );
}
